### ISSUE TITLE
Which install method is best?

### ISSUE THREAD

**Issue by jadomski** [nitaybz/homebridge-tado-ac-old#10]
In the readme there are two install methods shown
`npm install -g homebridge-tado-ac`
and
`sudo npm install -g https://github.com/nitaybz/homebridge-tado-ac.git`

I'm wondering whether there are any differences between them with your repository - i.e. which provides the newer and do either provide auto updating capabilities?

**Comment by nitaybz** [comment]
the one from git will always give you the most updated one:
`sudo npm install -g https://github.com/nitaybz/homebridge-tado-ac.git`
because I'm usually updating on git first...
but actually not both ways re the same version... I recommend to use sudo even in the first method, I changed it on the README file

**Comment by jadomski** [comment]
Do either methods support automatic updates?

**Comment by nitaybz** [comment]
I'm not familiar with automatic updates... sorry
