### ISSUE TITLE
When AC is off and ask to turn it off, the AC turns on

### ISSUE THREAD

**Issue by matthieulrg** [nitaybz/homebridge-tado-ac-old#16]
Hi,

I discovered a little problem with the plugin. I have a scene named "Good night" which turns off all my lights and all my AC with Tado. The problem is that sometimes, all the AC is already off and when I turn on the scene good night (which ask all the AC to turn off), sometimes they start, set to 16° and sometimes not.

I don't know if it's on your side or Apple side but it's really annoying. For example, when I tell to a light already off to turn off, she doesn't turn on, she stays off, why it's not the case for the AC? Anyone has the same issue ?

Thanks in advance,
Matt'

**Comment by nitaybz** [comment]
I'm very familiar with this issue... the problem comes from the Home app scene setup.

When you set the AC to off in the scene it also (always) give it a temperature degree.
When the scene is triggered it will shoot both OFF and the minimum temperature value, which ever comes last will determent the chosen command.

Unfortunately I don't know how to solve this issue from within my code, but luckily there is a work around!
You can edit the scene from any other homekit app like "Eve" which I recommend and remove the 
temperature value, which will leave you either with Power => OFF or Mode => OFF, each one of those (no need for both!) will turn off your AC safely.

Hope it will satisfy your needs...

**Comment by jadomski** [comment]
I can confirm that the Eve app workaround explained above works for me.

**Comment by matthieulrg** [comment]
Yup, working here too, thanks ! Maybe adding it to the tutorial ?

**Comment by nitaybz** [comment]
@matthieudu06 I think I solved this issue in version 1.3.2.
I did some workaround to overcome the Home app scene issue, but I think now you'll be able to set scenes through the Home app without editing in the Eve app.

Let me know if that did the trick...

**Comment by jadomski** [comment]
Issue is solved for me. Just created two new scenes in the Home app and they seem to work perfectly now.

**Comment by matthieulrg** [comment]
Issue solved for me too ! Thanks so much for your work !

**Comment by nitaybz** [comment]
hey Guys!
New version is available to download... v 2.0
this version require a whole new config, please read [README.md](https://github.com/nitaybz/homebridge-tado-ac/blob/master/README.md) file before installing.
`sudo npm install -g homebridge-tado-ac`

This version will give you much more control on your AC device including Fan mode, swing & rotation speed control.

I would love to get your feedback on that!

Please submit new issues (or feedback) to the [New Git](https://github.com/nitaybz/homebridge-tado-ac/issues) which has the same name but it's completely new. the [Old Git](https://github.com/nitaybz/homebridge-tado-ac-old) will not be supported anymore

Thanks a lot!
