### ISSUE TITLE
AC not responding ion homekit if set to AC mode from tado app

### ISSUE THREAD

**Issue by jetmcquack** [nitaybz/homebridge-tado-ac-old#9]
Hi, just a new issue to track, not so critical.
If you set AC to Fan mode in the tado app the AC will be "Not responding" in home kit. 
The situation will be back to normal in the same moment the ac is turned off or set to cool mode. 
have a great day!
F

**Comment by nitaybz** [comment]
I know... homekit thermostat does not have a fan state... I really wish someone could make the airConditioner characteristic available to homebridge, with that we could really make an AC accessory that has any state that AC has like fan/auto/dehydrate...
I could handle the fan like it's a cool mode or heat mode, butI don't think it will be appropriate

**Comment by nitaybz** [comment]
or maybe show it as auto?
what do you think?

**Comment by nitaybz** [comment]
try to install again from here:
`npm install -g https://github.com/nitaybz/homebridge-tado-ac`

**Comment by nitaybz** [comment]
I couldn't make it with Auto mode because auto mode requires a temperature, so I set it to OFF, any state that is not Cool or Heat will show as OFF, but at least it won't stuck the Home app.
I already checked it with my AC and it's working fine, so I uploaded it to npm and closing this issue, install new version with:
`sudo npm install -g homebridge-tado-ac`.

**Comment by jetmcquack** [comment]
hi, i don't know if this can help, i've seen you are in the discussion.

 https://github.com/KhaosT/HAP-NodeJS/issues/461

**Comment by nitaybz** [comment]
I'll find some time and play with it... it will be a whole new version and a lot of work... I hope I can find the time.
